from kalico import config


def isiks_tech_ouroboros(mcu):
    return config(
        "board_pins",
        "isiks-tech_ouroboros",
        mcu=mcu.name,
        aliases=dict(
            TH0="PB1",
            TH1="PB0",
            FAN="PE10",
            TMC1_TEMP="PC4",
            TMC2_TEMP="PC5",
            X_CS="PD0",
            X_STEP="PD4",
            X_DIR="PD3",
            X_EN="PD6",
            X_STOP="PD7",
            SW1="PD7",
            Y_CS="PD2",
            Y_STEP="PC12",
            Y_DIR="PC11",
            Y_EN="PD1",
            Y_STOP="PB3",
            SW2="PB3",
        ),
        aliases_exp=dict(
            EXP_0="<GND>",
            EXP_1="<GND>",
            EXP_2="PA4",
            EXP_3="PA5",
            EXP_4="PA6",
            EXP_5="PA7",
            EXP_6="PE14",
            EXP_7="PE15",
            EXP_8="<GND>",
            EXP_9="PB6",
            EXP_10="PB5",
            EXP_11="<GND>",
            EXP_12="PE8",
            EXP_13="PE7",
            EXP_14="<GND>",
            EXP_15="PE1",
            EXP_16="PE0",
            EXP_17="<GND>",
            EXP_18="PB9",
            EXP_19="PB8",
            EXP_20="<12V>",
            EXP_21="<12V>",
            EXP_22="<12V>",
            EXP_23="<MISO>",  # TODO: which bus? what?
            EXP_24="<MOSI>",  # TODO: which bus? what?
            EXP_25="<SCK>",  # TODO: which bus? what?
            EXP_26="PE3",
            EXP_27="PB2",
            EXP_28="PB1",
            EXP_29="PB10",
            EXP_30="PE9",
            EXP_31="<GND>",
            EXP_32="<GND>",
            EXP_33="<GND>",
            EXP_34="PB0",
            EXP_35="<GND>",
            EXP_36="<3.3V>",
            EXP_37="<3.3V>",
            EXP_38="<5V>",
            EXP_39="<5V>",
        ),
    )
